apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: cluster-google
  labels:
    provider: google
    cluster: gke
spec:
  compositeTypeRef:
    apiVersion: devopstoolkitseries.com/v1alpha1
    kind: CompositeKubernetesCluster
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels
  resources:
  - name: gkecluster
    base:
      apiVersion: container.gcp.crossplane.io/v1beta1
      kind: Cluster
      metadata:
        name: gkecluster
      spec:
        forProvider:
          location: us-east1
          network: "projects/magnetic-nimbus-389901/global/networks/network"
          subnetwork: "projects/magnetic-nimbus-389901/regions/europe-west1/subnetworks/subnet"
          masterAuth:
            clientCertificateConfig:
              issueClientCertificate: false
          initialClusterVersion: latest
        providerConfigRef:
          name: gcp-provider
    patches:
    - type: PatchSet
      patchSetName: metadata
    - fromFieldPath: spec.parameters.version
      toFieldPath: spec.forProvider.initialClusterVersion
    - type: ToCompositeFieldPath
      fromFieldPath: metadata.annotations[crossplane.io/external-name]
      toFieldPath: status.clusterName
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.status
      toFieldPath: status.controlPlaneStatus
    connectionDetails:
    - fromConnectionSecretKey: kubeconfig
    readinessChecks:
    - type: MatchString
      fieldPath: "status.atProvider.status"
      matchString: "RUNNING"
  - name: nodepool
    base:
      apiVersion: container.gcp.crossplane.io/v1beta1
      kind: NodePool
      spec:
        forProvider:
          locations:
          - europe-west1-c
          - europe-west1-d
          clusterSelector:
            matchControllerRef: true
          config:
            preemptible: true
            oauthScopes:
            - https://www.googleapis.com/auth/cloud-platform
          autoscaling:
            enabled: true
            maxNodeCount: 3
          management:
            autoRepair: true
            autoUpgrade: false
        providerConfigRef:
          name: gcp-provider
    patches:
    - type: PatchSet
      patchSetName: metadata
    - fromFieldPath: spec.parameters.minNodeCount
      toFieldPath: spec.forProvider.initialNodeCount
    - fromFieldPath: spec.parameters.minNodeCount
      toFieldPath: spec.forProvider.autoscaling.minNodeCount
    - fromFieldPath: spec.parameters.nodeSize
      toFieldPath: spec.forProvider.config.machineType
      transforms:
      - type: map
        map:
          small: e2-standard-2
          medium: e2-standard-4
          large: e2-standard-16
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.status
      toFieldPath: status.nodePoolStatus
    readinessChecks:
    - type: MatchString
      fieldPath: status.atProvider.status
      matchString: RUNNING
  writeConnectionSecretsToNamespace: crossplane-system
    
