---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: port-k8s-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    chart: port-k8s-exporter
    repoURL: https://port-labs.github.io/helm-charts
    targetRevision: 0.1.13
    helm:
      releaseName: port-k8s-exporter
      values: |-
        installCRDs: true
        secret:
          secrets:
            portClientId: WL17EYqO9sHE1YuFCW3E06iiVvct1nu6
            portClientSecret: RmD8oID7s7HBD7pcQx5vJAzW9VxtAQvxZ1EXnic1V5R4MZ3ZtTawZtJlZf1Fm1fh
        configMap:
          name: config-k8s.yaml
          # config: |-
          config:
            resources:
              - kind: v1/namespaces
                selector:
                  query: .metadata.name | contains("kube-system")
                port:
                  entity:
                    mappings:
                      - identifier: "coecluster"
                        title: "coecluster"
                        blueprint: "cluster"
                        properties:
                          provider: '"n/a"'

              - kind: v1/secrets
                selector:
                  query: .type == "connection.crossplane.io/v1alpha1"
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name
                        title: .metadata.name
                        blueprint: '"cluster"'
                        properties:
                          kube-config: .data.kubeconfig
              - kind: v1/namespaces
                selector:
                  query: .metadata.annotations.environment == "true"
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-" + "coecluster"
                        title: .metadata.name
                        blueprint: '"environment"'
                        relations:
                          cluster: '"coecluster"'
              - kind: v1/namespaces
                selector:
                  query: .metadata.name | startswith("kube") | not
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-" + "coecluster"
                        title: .metadata.name
                        blueprint: '"namespace"'
                        properties:
                          creationTimestamp: .metadata.creationTimestamp
                          labels: .metadata.labels
                        relations:
                          Cluster: '"coecluster"'
              - kind: devopstoolkitseries.com/v1alpha1/appclaims
                selector:
                  query: .spec.compositionSelector.matchLabels.type == "backend-db-google"
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-appclaim-" + .metadata.namespace + "-" + "coecluster"
                        title: .metadata.name
                        icon: '"Deployment"'
                        blueprint: '"backend-app"'
                        properties:
                          url: '"https://github.com/" + .metadata.annotations.gitHubOrg + "/" + .metadata.annotations.gitHubRepo'
                          language: '"Go"'
                          host: .spec.parameters.host
                          db-version: .spec.parameters.db.version
                          db-size: .spec.parameters.db.size
                          labels: .metadata.labels
                        relations:
                          environment: .metadata.namespace + "-" + "coecluster"
              - kind: v1/nodes
                port:
                  entity:
                    mappings:
                      - identifier: (.metadata.name) | (split(".")|join("_")) + "-" + "coecluster"
                        title: .metadata.name + "-" + "coecluster"
                        icon: '"Node"'
                        blueprint: '"node"'
                        properties:
                          creationTimestamp: .metadata.creationTimestamp
                          totalCPU: .status.allocatable.cpu
                          totalMemory: .status.allocatable.memory
                          labels: .metadata.labels
                          kubeletVersion: .status.nodeInfo.kubeletVersion | split("-") | .[0]
                          ready: .status.conditions[] | select(.type == "Ready") | .status
                        relations:
                          Cluster: '"coecluster"'
              - kind: v1/pods
                selector:
                  query: .metadata.namespace | startswith("kube") | not 
                port:
                  entity:
                    mappings:
                      - identifier: .metadata.name + "-" + .metadata.namespace + "-" + "coecluster"
                        title: .metadata.name
                        icon: '"Microservices"'
                        blueprint: '"pod"'
                        properties:
                          startTime: .status.startTime
                          phase: .status.phase
                          labels: .metadata.labels
                          containers: (.spec.containers | map({image, resources})) + .status.containerStatuses | group_by(.image) | map(add)
                          conditions: .status.conditions
                        relations:
                          Node: (.spec.nodeName) | (split(".")|join("_")) + "-" + "coecluster"
  destination:
    server: https://kubernetes.default.svc
    namespace: port-k8s-exporter
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
