---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: schema-hero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    repoURL: https://github.com/tapasmishraarcgitops/idp-demo.git
    targetRevision: HEAD
    path: schema-hero
  destination:
    server: https://kubernetes.default.svc
    namespace: schemahero-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
