name: Create App With DB
on:
  workflow_dispatch:
    inputs:
      repo-org:
        required: true
        description: "Repository organization"
        type: string
        default: "tapasmishraarcgitops"
      repo-user:
        required: true
        description: "Repository user"
        type: string
        default: "tapasmishraarc"
      repo-name:
        required: true
        description: "Repository name"
        type: string
        default: "idp-demo-app"
      image-repo:
        required: true
        description: "Image repository"
        type: string
        default: "docker.io/tapasmishra"
      environment:
        required: true
        description: "Environment to deploy app to (production, staging, development)"
        type: string
        default: "production"
      host:
        required: true
        description: "Application host name"
        type: string
        default: "acme.com"
      db-version:
        required: true
        description: "Database version"
        type: string
        default: "13"
      db-size:
        required: true
        description: "Database size (small, medium, large)"
        type: string
        default: "medium"
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Create repo
        run: |
          chmod +x scripts/create-repo-app-db.sh
          ./scripts/create-repo-app-db.sh ${{ secrets.ORG_ADMIN_TOKEN }} ${{ inputs.repo-org }} ${{ inputs.repo-user }} ${{ secrets.DOCKERHUB_USER }} ${{ inputs.repo-name }} ${{ inputs.image-repo }} ${{ inputs.host }} ${{ inputs.db-version }} ${{ inputs.db-size }}
      - name: Create Argo CD App
        run: |
          chmod +x scripts/create-argocd-app.sh
          ./scripts/create-argocd-app.sh ${{ inputs.repo-name }} ${{ inputs.repo-org }} ${{ inputs.repo-name }} ${{ inputs.environment }}
      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Deploy ${{ inputs.name }} to ${{ inputs.environment }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
